# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FootyHi-Lite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootyHi-Lite
  pod ‘Parse’
  pod ‘AlamofireImage’

  target 'FootyHi-LiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FootyHi-LiteUITests' do
    # Pods for testing
  end

end
